# Generated by Django 5.2.7 on 2025-10-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedcontent',
            name='requested_type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('TEXT', 'Text')], default='VIDEO', max_length=20),
        ),
        migrations.AlterField(
            model_name='downloadedcontent',
            name='source_url',
            field=models.URLField(max_length=1024),
        ),
    ]
