# Generated by Django 5.2.7 on 2025-10-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_downloadedcontent_requested_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadedcontent',
            name='requested_type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('TEXT', 'Text')], max_length=20),
        ),
    ]
