# Generated by Django 5.1.13 on 2025-11-04 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('media_url', models.URLField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('file_size_mb', models.FloatField(blank=True, null=True)),
                ('storage_url', models.URLField(blank=True, help_text='URL to media in S3/Supabase storage', null=True)),
                ('storage_provider', models.CharField(choices=[('aws_s3', 'AWS S3'), ('supabase', 'Supabase Storage'), ('none', 'No Storage')], default='none', help_text='Storage provider used for this content', max_length=20)),
                ('file_size_bytes', models.BigIntegerField(blank=True, help_text='Actual file size in bytes', null=True)),
                ('published_at', models.DateTimeField()),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('topics', models.JSONField(default=list)),
                ('guid', models.CharField(max_length=500, unique=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contentsource')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['source', '-published_at'], name='core_conten_source__1af2e9_idx'), models.Index(fields=['guid'], name='core_conten_guid_95349f_idx')],
            },
        ),
    ]
