# Generated by Django 5.1.13 on 2025-11-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloaditem',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if download failed', null=True),
        ),
        migrations.AddField(
            model_name='downloaditem',
            name='file_size_bytes',
            field=models.BigIntegerField(blank=True, help_text='Size of downloaded file in bytes', null=True),
        ),
        migrations.AddField(
            model_name='downloaditem',
            name='local_file_path',
            field=models.CharField(blank=True, help_text='Local path to downloaded file', max_length=500, null=True),
        ),
    ]
