# Generated by Django 5.1.15 on 2025-12-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_downloaditem_error_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentsource",
            name="type",
            field=models.CharField(
                choices=[
                    ("podcast", "Podcast"),
                    ("article", "Article"),
                    ("video", "Video"),
                ],
                max_length=20,
            ),
        ),
    ]
