# Generated by Django 5.1.15 on 2025-12-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_contentsource_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentsource",
            name="type",
            field=models.CharField(
                choices=[
                    ("podcast", "Podcast"),
                    ("article", "Article"),
                    ("video", "Video"),
                    ("meme", "Meme"),
                ],
                max_length=20,
            ),
        ),
    ]
