# Generated by Django 5.1.15 on 2025-12-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_contentsource_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloaditem",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Content description or article summary",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contentsource",
            name="type",
            field=models.CharField(
                choices=[
                    ("podcast", "Podcast"),
                    ("article", "Article"),
                    ("video", "Video"),
                    ("meme", "Meme"),
                    ("news", "News"),
                ],
                max_length=20,
            ),
        ),
    ]
