# Generated by Django 5.0.6 on 2025-11-03 06:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_category_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloaditem",
            name="download_type",
            field=models.CharField(
                choices=[("VIDEO", "Video"), ("AUDIO", "Audio"), ("TEXT", "Text")],
                default="VIDEO",
                help_text="Type requested from downloader service",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="downloaditem",
            name="downloader_task_id",
            field=models.UUIDField(
                blank=True, help_text="UUID from downloader service", null=True
            ),
        ),
        migrations.AddField(
            model_name="downloaditem",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional metadata from downloader service",
            ),
        ),
        migrations.AlterField(
            model_name="downloaditem",
            name="available_from",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When content becomes available",
            ),
        ),
        migrations.AlterField(
            model_name="downloaditem",
            name="media_url",
            field=models.URLField(
                blank=True, help_text="S3 URL from downloader service", null=True
            ),
        ),
        migrations.AlterField(
            model_name="downloaditem",
            name="source",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: ContentSource for automated items, null for manual URL entries",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.contentsource",
            ),
        ),
        migrations.AlterField(
            model_name="downloaditem",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Fetched from downloader service",
                max_length=300,
                null=True,
            ),
        ),
    ]
